checks:
  php:
    code_rating: true
    duplication: false

filter:
  excluded_paths:
    - tests/*
    - examples/*
    - vendor/*

build:

  environment:
    php: '7.0.8'

  dependencies:
    before:
      - 'sudo apt-get install -y lsof'
      - 'composer install'
      - './vendor/bin/codecept build'
      - '(cd tests/assets/www && php -S localhost:8080) &'

  tests:
    override:
      -
        command: 'php vendor/bin/codecept run unit --coverage --coverage-xml'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'php-clover'
