<?php

namespace mpyw\Cowitter\Helpers;

use mpyw\Cowitter\HttpException;
use mpyw\Cowitter\Response;
use mpyw\Cowitter\Media;

class ResponseBodyDecoder
{
    protected $response;
    protected $ch;
    protected $info;
    protected $bodyBuffer;

    public static function getDecodedResponse(Response $response, $ch, $body_buffer = null)
    {
        $static = new static($response, $ch, $body_buffer);
        return $response->withDecodedContent($static->normalizeImpl());
    }

    protected function __construct(Response $response, $ch, $body_buffer = null)
    {
        $this->response = $response;
        $this->ch = $ch;
        $this->info = curl_getinfo($ch);
        $this->bodyBuffer = $body_buffer === null ? $response->getRawContent() : $body_buffer;
    }

    protected function normalizeImpl()
    {
        if ($this->bodyBuffer === '') {
            return $this->handleEmptyBody();
        }
        if (preg_match('@\A(?:image|video)/@', $this->info['content_type'])) {
            return new Media($this->info['content_type'], $this->bodyBuffer);
        }
        if (null !== $obj = $this->handleJsonAndXml()) {
            return $obj;
        }
        if (strip_tags($this->bodyBuffer) === $this->bodyBuffer) {
            return $this->handleText();
        }
        if ($this->info['http_code'] >= 400 && preg_match("@<(?:pre|h1)>([^<]++)</(?:pre|h1)>@", $this->bodyBuffer, $matches)) {
            throw new HttpException(trim($matches[1]), -1, $this->ch, $this->response);
        }
        throw new \UnexpectedValueException('Malformed response detected: ' . $this->bodyBuffer);
    }

    protected function handleEmptyBody()
    {
        if ($this->info['http_code'] >= 200 && $this->info['http_code'] <= 204) {
            $message = 'Your request has been successfully sent. (This is a message generated by Cowitter)';
            return (object)['message' => $message];
        }
        throw new HttpException(
            "The server returned the status {$this->info['http_code']} with empty response. (This is a message generated by Cowitter)",
            -1,
            $this->ch,
            $this->response
        );
    }

    protected function handleJsonAndXml()
    {
        $orig = libxml_use_internal_errors(true);
        try {
            if (
                null  === $obj = json_decode(preg_replace('@\A/\*{2}/[^(]++\((.+)\);\z@s', '$1', $this->bodyBuffer)) and
                false === $obj = json_decode(json_encode(simplexml_load_string($this->bodyBuffer)))
            ) {
                return;
            }
        } finally {
            libxml_clear_errors();
            libxml_use_internal_errors($orig);
        }
        if (isset($obj->error)) {
            throw new HttpException($obj->error, -1, $this->ch, $this->response);
        }
        if (isset($obj->errors)) {
            if (is_string($obj->errors)) {
                throw new HttpException($obj->errors, -1, $this->ch, $this->response);
            }
            $messages = [];
            foreach ($obj->errors as $error) {
                $messages[] = $error->message;
            }
            $current = current($obj->errors);
            throw new HttpException(
                implode("\n", $messages),
                $current === false ? -1 : $current->code,
                $this->ch,
                $this->response
            );
        }
        return $obj;
    }

    protected function handleText()
    {
        parse_str($this->bodyBuffer, $obj);
        $obj = (object)$obj;
        if (isset($obj->oauth_token, $obj->oauth_token_secret)) {
            return $obj;
        }
        throw new HttpException(trim($this->bodyBuffer), -1, $this->ch, $this->response);
    }
}
